name: "Grid.ai Run Artifact"
inputs:
  # required
  script-name:
    required: true
    default: "run.py"
    type: string   
    description: "The name of the script to run"
  script-dir:
    required: false
    default: "${GITHUB_WORKSPACE}"
    type: string   
    description: "Directory where the script is at"
  # optional    
  cluster-name:
    required: false
    default: ""
    type: string    
    description: "Arguments to grid run command"
  grid-args:
    required: false
    default: "--localdir --instance_type t2.medium --dependency_file requirements.txt"
    type: string    
    description: "Arguments to grid run command"
  script-args:
    required: false
    default: ""
    type: string
    description: "Arguments to the script"
  success-status:
    required: false
    default: "succeeded"
    type: string               
    description: "grid run status text for successful execution"
outputs:
  # from obj-create step
  script:
    value: ${{ steps.gridai-obj-create.outputs.script }}
    description: "script name"
  instance_type:
    value: ${{ steps.gridai-obj-create.outputs.instance_type }}
    description: "script name"
  use_spot:
    value: ${{ steps.gridai-obj-create.outputs.use_spot }}
    description: "script name"
  cloud_provider:
    value: ${{ steps.gridai-obj-create.outputs.cloud_provider }}
    description: "script name"
  grid_name:
    value: ${{ steps.gridai-obj-create.outputs.grid_name }}
    description: "script name" 
  datastore_name:
    value: ${{ steps.gridai-obj-create.outputs.datastore_name }}
    description: "script name"
  datastore_version:
    value: ${{ steps.gridai-obj-create.outputs.datastore_version }}
    description: "script name"
  datastore_mount_dir:
    value: ${{ steps.gridai-obj-create.outputs.datastore_mount_dir }}
    description: "script name"                            
  # from obj-status step
  obj-type:
    value: ${{ steps.gridai-obj-status.outputs.obj-type }}
    description: "object id searched for"
  obj-id:
    value: ${{ steps.gridai-obj-status.outputs.obj-id }}
    description: "object id searched for"
  obj-status:
    value: ${{ steps.gridai-obj-status.outputs.obj-status }}
    description: "comma delimited status all of objects. ex: succeeded,succeeded,stopped"
  obj-tally:
    value: ${{ steps.gridai-obj-status.outputs.obj-tally }}
    description: "comma delimited tally status codes. ex: 2 succeeded,1 stopped"
  obj-summary:
    value: ${{ steps.gridai-obj-status.outputs.obj-summary }}
    description: "comma delimited unique status codes. ex: succeeded,stopped"
  obj-exit-code:
    value: ${{ steps.gridai-obj-status.outputs.obj-exit-code }}
    description: "0 if exited finding the supplied status, 1 otherwise"   
runs:
  using: "composite"
  steps:
    - run: |
        if [ -z "${{ inputs.cluster-name }}" ]; then
          echo BYOC_CLUSTER="" >> $GITHUB_ENV
        else
          echo BYOC_CLUSTER="--cluster ${{ inputs.cluster-name }}" >> $GITHUB_ENV
        fi
      shell: bash  
    - id: gridai-obj-create
      run: |
        cd ${{ inputs.script-dir }}
        gridai.py cli "grid run --ignore_warnings ${BYOC_CLUSTER} ${{ inputs.grid-args }} ${{ inputs.script-name }} ${{ inputs.script-args }}" status_to_kv --gha True
      shell: bash  

    - id: gridai-obj-status
      run: |
        gridai.py run ${{ steps.gridai-obj-create.outputs.grid_name }} --gha True --log_level DEBUG
      shell: bash  

    - run: |
        if [ -z "$(echo ${{ steps.gridai-obj-status.outputs.obj-summary }} | grep '${{ inputs.success-status }}')" ]; then
          exit 1
        fi             
      shell: bash  

    - run: |
        cd ${{ inputs.script-dir }}
        pwd
        gridai.py cli "grid artifacts ${{ steps.gridai-obj-create.outputs.grid_name }}"
        if [[ $? != 0 ]]; then
          echo "Error: ${run_name} artifacts not found"
          exit 1
        fi
        find grid_artifacts -type f -print | sort
      shell: bash  
