name: 'Grid.ai Run Test'
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  unittests:
    strategy:
      matrix:
        os: [ubuntu-latest]   #,macos-latest,windows-latest]
        python-version: [3.8] #,3.9]       
        python-venv: [""]     #,"venv"]       
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2     
      - uses: gridai-actions/gridai-login@main
        with:
          python-version: ${{ matrix.python-version }}
          python-venv: ${{ matrix.python-venv }}
          gridai-username: ${{ secrets.GRIDAI_USERNAME }} 
          gridai-key: ${{ secrets.GRIDAI_KEY }} 
      - run: |
          mkdir hello
          cd hello
          echo "print ('hello'); f = open('weights.pt', 'a'); f.write('fake weights'); f.close()" > run.py
          echo "os" > requirements.txt
      - uses: gridai-actions/gridai-run@main