# Trigger
name: 'Grid.ai Run Git Clone'
on:
  push:
    paths:
      - action.yml
      - .github/workflows/unittest-gitclone.yml

jobs:
  unittests:
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        os: [ubuntu-latest]   #, macos-latest,windows-latest]
        python-version: [3.8] # , 3.9]       
        python-venv: ["venu"] #,""]       
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    steps:
      - uses: gridai-actions/gridai-login@main
        with:
          python-version: ${{ matrix.python-version }}
          python-venv: ${{ matrix.python-venv }}
          gridai-username: ${{ secrets.GRIDAI_USERNAME }} 
          gridai-key: ${{ secrets.GRIDAI_KEY }} 
      - run: |
          git clone https://github.com/robert-s-lee/hello
          cd hello
          echo "CLONE_PWD=$(pwd)" >> $GITHUB_ENV
          ls -R
      - uses: gridai-actions/gridai-run@main
        with:
          script-dir: ${CLONE_PWD}
          script-name: hello.py
